### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PGGANGeneratorModel:

### ISSUE THREAD

**Issue by c1a1o1** [ShenYujun/InterFaceGAN#7]
E:\Users\Raytine\Anaconda3\python.exe F:/expression/InterFaceGAN-master/edit.py -m pggan_celebahq -b boundaries/pggan_celebahq_smile_boundary.npy -n 10 -o results/pggan_celebahq_smile_editing
[2019-08-12 10:30:13,999][INFO] Initializing generator.
[2019-08-12 10:30:23,051][INFO] Loading tensorflow model from `{self.tf_model_path}`.
[2019-08-12 10:30:28,891][INFO] Successfully loaded!
[2019-08-12 10:30:28,892][INFO] Converting tensorflow model to pytorch version.
[2019-08-12 10:30:29,095][INFO] Successfully converted!
[2019-08-12 10:30:29,095][INFO] Saving pytorch model to `{self.model_path}`.
[2019-08-12 10:30:29,120][INFO] Successfully saved!
[2019-08-12 10:30:29,120][INFO] Loading pytorch model from `{self.model_path}`.
Traceback (most recent call last):
  File "F:/expression/InterFaceGAN-master/edit.py", line 112, in <module>
    main()
  File "F:/expression/InterFaceGAN-master/edit.py", line 63, in main
    model = PGGANGenerator(args.model_name, logger)
  File "F:\expression\InterFaceGAN-master\models\pggan_generator.py", line 24, in __init__
    super().__init__(model_name, logger)
  File "F:\expression\InterFaceGAN-master\models\base_generator.py", line 96, in __init__
    self.convert_tf_model()
  File "F:\expression\InterFaceGAN-master\models\pggan_generator.py", line 70, in convert_tf_model
    self.load()
  File "F:\expression\InterFaceGAN-master\models\pggan_generator.py", line 34, in load
    self.model.load_state_dict(torch.load(self.model_path))
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PGGANGeneratorModel:
	Unexpected key(s) in state_dict: "layer5.conv.weight", "layer18.conv.weight", "layer2.conv.weight", "layer15.wscale.bias", "layer18.wscale.bias", "layer4.wscale.bias", "layer6.wscale.bias", "layer1.conv.weight", "layer8.conv.weight", "layer14.wscale.bias", "layer10.wscale.bias", "layer8.wscale.bias", "layer15.conv.weight", "output_1024x1024.conv.weight", "output_1024x1024.wscale.bias", "layer7.conv.weight", "layer9.conv.weight", "layer9.wscale.bias", "layer17.conv.weight", "layer13.wscale.bias", "layer12.wscale.bias", "layer14.conv.weight", "layer16.wscale.bias", "layer11.wscale.bias", "layer16.conv.weight", "layer10.conv.weight", "layer6.conv.weight", "layer17.wscale.bias", "layer4.conv.weight", "layer13.conv.weight", "layer5.wscale.bias", "layer2.wscale.bias", "layer3.wscale.bias", "layer12.conv.weight", "layer1.wscale.bias", "layer11.conv.weight", "layer7.wscale.bias", "layer3.conv.weight".

**Comment by ShenYujun** [comment]
It's weird. Since you have already successfully saved the model, it should be able to load as well. BTW, which version of python are you using? Why `f-string` doesn't work according to your log message? We recommand to use `python3.7`.

**Comment by c1a1o1** [comment]
I only use a GPU!

**Comment by SystemErrorWang** [comment]
similar problem here. I can run 'edit.py' without any problem and successfully saved 3 pth files. But when I tried to load stylegan_celebahq.pth and stylegan_ffhq.pth, pytorch returned this message:
```
RuntimeError: Error(s) in loading state_dict for StyleGANGeneratorModel:
        Missing key(s) in state_dict: "truncation.truncation".
```
btw, the pggan_celeba.pth can be loaded without problem.

**Comment by ShenYujun** [comment]
@SystemErrorWang I am a little bit confused. You can successfully run `edit.py` means this repo works well. By saying "when I tried to load stylegan_celebahq.pth and stylegan_ffhq.pth", do you mean you want to load them beyond this repo? If so, please check `models/stylegan_generator.py` to see how to load the model.

```
def __init__(self, model_name, logger=None):
  ...
  self.model_specific_vars = ['truncation.truncation']
  ...

def load(self):
  ...
  state_dict = torch.load(self.model_path)
  for var_name in self.model_specific_vars:
    state_dict[var_name] = self.model.state_dict()[var_name]
  ...
```

Basically, `truncation.truncation` is independent from the pre-trained weights. Or say, client can use the same pre-trained model but with different truncation weights. As a result, we do not save the variable `truncation.truncation` in the `pth` file. Instead, this variable is initialized at the same time when the model is initialized.
