### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by c1a1o1** [ShenYujun/InterFaceGAN#8]
E:\Users\Raytine\Anaconda3\python.exe F:/expression/InterFaceGAN-master/edit.py -m stylegan_celebahq -b boundaries/stylegan_celebahq_pose_boundary -n 10 -o results/stylegan_celebahq_smile_editing
[2019-08-12 13:50:32,896][INFO] Initializing generator.
[2019-08-12 13:50:34,279][INFO] Loading tensorflow model from `{self.tf_model_path}`.
Traceback (most recent call last):
  File "F:/expression/InterFaceGAN-master/edit.py", line 114, in <module>
    main()
  File "F:/expression/InterFaceGAN-master/edit.py", line 68, in main
    model = StyleGANGenerator(args.model_name, logger)
  File "F:\expression\InterFaceGAN-master\models\stylegan_generator.py", line 42, in __init__
    super().__init__(model_name, logger)
  File "F:\expression\InterFaceGAN-master\models\base_generator.py", line 96, in __init__
    self.convert_tf_model()
  File "F:\expression\InterFaceGAN-master\models\stylegan_generator.py", line 73, in convert_tf_model
    _, _, tf_model = pickle.load(f)
  File "models/stylegan_tf_official\dnnlib\__init__.py", line 20
    submit_config: SubmitConfig = None # Package level variable for SubmitConfig which is only valid when inside the run function.
                 ^
SyntaxError: invalid syntax

**Comment by ShenYujun** [comment]
Codes inside folder `stylegan_tf_official` are officially released by StyleGAN. If you cannot convert tensorflow model correctly, maybe you can check dependencies from their repo.
